/**
 * generateReact — Exports the current layout config as a React .tsx component file.
 */
import type {
  LayoutConfig,
  SectionConfig,
  StatsRowOptions,
  ChartGridOptions,
  FormFieldsOptions,
  CTABlockOptions,
} from '../types';

export function generateReact(config: LayoutConfig): string {
  const imports = new Set<string>([
    'UBSThemeProvider',
    'UBSGlobalStyles',
    'Typography',
  ]);
  const iconImports = new Set<string>();

  if (config.includeNavbar) { imports.add('Navbar'); imports.add('Logo'); iconImports.add('Search'); iconImports.add('Bell'); iconImports.add('User'); }
  if (config.includeFooter) imports.add('Footer');
  if (config.includeImpulse) imports.add('Impulse');
  if (config.includeMovingFrame) imports.add('MovingFrame');

  // Always need PageHeader for most page types
  imports.add('PageHeader');
  imports.add('SectionWrapper');
  imports.add('Grid');
  imports.add('Button');
  imports.add('CTA');

  config.sections.forEach((s) => {
    switch (s.type) {
      case 'stats-row': imports.add('Stat'); break;
      case 'chart-grid': imports.add('DataViz'); break;
      case 'feature-grid': imports.add('Card'); break;
      case 'form-fields':
        const ff = s.options as FormFieldsOptions;
        ff.fieldTypes.forEach((t) => {
          switch (t) {
            case 'text': case 'email': imports.add('Input'); break;
            case 'select': imports.add('Select'); break;
            case 'textarea': imports.add('Textarea'); break;
            case 'checkbox': imports.add('Checkbox'); break;
            case 'radio': imports.add('Radio'); imports.add('RadioGroup'); break;
            case 'toggle': imports.add('Toggle'); break;
            case 'date': imports.add('DatePicker'); break;
          }
        });
        break;
      case 'table': imports.add('Table'); break;
      case 'content-block': break;
      case 'card-grid': imports.add('Card'); break;
      case 'cta-block': break;
    }
  });

  const componentImports = Array.from(imports).sort().join(',\n  ');
  const iconImportStr = iconImports.size > 0
    ? `\nimport {\n  ${Array.from(iconImports).sort().join(',\n  ')},\n} from '@ubs/design-system';\n`
    : '';

  const sectionsCode = config.sections.map((s, i) => renderSectionCode(s, i)).join('\n\n');

  return `/**
 * Auto-generated UBS Layout Component
 * Generated by UBS Layout Preview App
 */
import React from 'react';
import {
  ${componentImports},
} from '@ubs/design-system';
${iconImportStr}
export default function GeneratedLayout() {
  return (
    <UBSThemeProvider defaultColourMode="${config.darkMode ? 'dark' : 'light'}">
      <UBSGlobalStyles />
      <div style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column' }}>
        ${config.includeNavbar ? `{/* Navbar */}
        <Navbar
          logo={<Logo variant="full" colour="${config.darkMode ? 'white' : 'black'}" size={80} />}
          items={[
            { label: 'Home', href: '/', active: true },
            { label: 'Portfolio', href: '/portfolio' },
            { label: 'Markets', href: '/markets' },
            { label: 'Research', href: '/research' },
          ]}
          actions={
            <div style={{ display: 'flex', gap: 12, alignItems: 'center' }}>
              <Search size={20} />
              <Bell size={20} />
              <User size={20} />
            </div>
          }
          sticky
          variant="${config.darkMode ? 'dark' : 'light'}"
        />` : ''}

        {/* Page Header */}
        <PageHeader
          title="${config.title || 'Untitled Page'}"
          ${config.subtitle ? `subtitle="${config.subtitle}"` : ''}
          variant="${config.includeImpulse ? 'impulse' : 'default'}"
          breadcrumbs={[
            { label: 'Home', href: '/' },
            { label: '${config.title || 'Page'}' },
          ]}
        />

        <main style={{ flex: 1 }}>
${sectionsCode}
        </main>

        ${config.includeFooter ? `{/* Footer */}
        <Footer
          links={[
            { group: 'Wealth Management', items: [
              { label: 'Investment Advisory', href: '/advisory' },
              { label: 'Portfolio Management', href: '/portfolio' },
            ]},
            { group: 'Services', items: [
              { label: 'Online Banking', href: '/banking' },
              { label: 'Mobile App', href: '/app' },
            ]},
          ]}
          copyright="© 2026 UBS Group AG. All rights reserved."
          showLogo
        />` : ''}
      </div>
    </UBSThemeProvider>
  );
}
`;
}

function renderSectionCode(section: SectionConfig, _index: number): string {
  const bg = section.type === 'stats-row' ? 'pastel1' : 'white';

  let inner = '';
  switch (section.type) {
    case 'stats-row': {
      const opts = section.options as StatsRowOptions;
      inner = `<Grid columns={{ mobile: 1, tablet: 2, desktop: 3, wide: ${opts.count} }} gap="medium">
              {/* Add Stat components here */}
              <Stat label="Total AUM" value="$2.4B" change={{ value: 12.3, direction: 'up' }} size="lg" />
            </Grid>`;
      break;
    }
    case 'chart-grid': {
      const opts = section.options as ChartGridOptions;
      inner = `<Grid columns={{ mobile: 1, tablet: 2 }} gap="large">
              <DataViz
                type="${opts.chartType}"
                data={[
                  { label: 'Equities', value: 42 },
                  { label: 'Fixed Income', value: 28 },
                  { label: 'Cash', value: 8 },
                ]}
                colourSequence="multichrome"
              />
            </Grid>`;
      break;
    }
    case 'feature-grid': {
      inner = `<Grid columns={{ mobile: 1, tablet: 2, desktop: 3 }} gap="medium">
              <Card variant="default" padding="medium" hoverable>
                <Typography variant="subheadline2">Feature Title</Typography>
                <Typography variant="body2">Feature description goes here.</Typography>
              </Card>
            </Grid>`;
      break;
    }
    case 'table': {
      inner = `<Table
              columns={[
                { key: 'name', header: 'Client', sortable: true },
                { key: 'portfolio', header: 'Portfolio Value', align: 'right', sortable: true },
                { key: 'ytdReturn', header: 'YTD Return', align: 'right' },
              ]}
              data={[
                { name: 'Heinrich Müller', portfolio: 'CHF 12,450,000', ytdReturn: '+8.4%' },
              ]}
              striped
              hoverable
            />`;
      break;
    }
    case 'cta-block': {
      const opts = section.options as CTABlockOptions;
      inner = `<div style={{ display: 'flex', justifyContent: 'center', padding: '24px 0' }}>
              <CTA variant="${opts.variant}" label="${opts.label}" href="#" size="lg" animated />
            </div>`;
      break;
    }
    default:
      inner = `{/* ${section.type} content */}
            <Typography variant="body1">Section content goes here.</Typography>`;
  }

  return `          {/* ${section.title || section.type} */}
          <SectionWrapper title="${section.title}" padding="lg" background="${bg}">
            ${inner}
          </SectionWrapper>`;
}
